M48
; DRILL file {KiCad 9.0.7-9.0.7~ubuntu24.04.1} date 2026-01-18T13:51:05+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-01-18T13:51:05+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7-9.0.7~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X211.5Y-96.0
X217.28Y-96.0
M30
