(part "W25Q128JVSIM_TR"
    (packageRef "SOIC127P790X216-8N")
    (interface
        (port "1" (symbPinId 1) (portName "/CS") (portType INOUT))
        (port "2" (symbPinId 2) (portName "DO_(IO1)") (portType INOUT))
        (port "3" (symbPinId 3) (portName "/WP_(IO2)") (portType INOUT))
        (port "4" (symbPinId 4) (portName "GND") (portType INOUT))
        (port "5" (symbPinId 5) (portName "DI_(IO0)") (portType INOUT))
        (port "6" (symbPinId 6) (portName "CLK") (portType INOUT))
        (port "7" (symbPinId 7) (portName "/HOLD_OR_/RESET_(IO3)") (portType INOUT))
        (port "8" (symbPinId 8) (portName "VCC") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Winbond")
    (property "Manufacturer_Part_Number" "W25Q128JVSIM TR")
    (property "Mouser_Part_Number" "454-W25Q128JVSIMTR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Winbond/W25Q128JVSIM-TR?qs=qSfuJ%252Bfl%2Fd6ji9IuruL6Zg%3D%3D")
    (property "Arrow_Part_Number" "W25Q128JVSIM TR")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/w25q128jvsimtr/winbond-electronics?utm_currency=USD&region=nac")
    (property "Description" "3V 128M-BIT SERIAL FLASH MEMORY WITH DUAL/QUAD SPI & QPI & DTR")
    (property "Datasheet_Link" "http://www.winbond.com/resource-files/w25q128jv%20dtr%20revb%2011042016.pdf")
    (property "symbolName1" "W25Q128JVSIM_TR")
)
